browsers:
  - name: chrome
    version: 39..latest
  - name: ie
    version: 8..latest
  - name: firefox
    version: 34..latest
  - name: safari
    version: 5..latest
  - name: iphone
    version: 7.1..latest
  - name: ipad
    version: 7.1..latest
  - name: android
    version: 4.1..latest