# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

# Coverage report
after_success:
  - npm run report
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    secure: 4ydD2JBKNT9WfAwn4kZ4j/QpSfbJs8Bbb87byHWUOj6klrSMdLtlykzuqioSXW6ZNNqNgCh4YwhQjNuemUKd4RiyyJdxOWuaxpQxQU1KSyZrLbY+Zad++vFlr7PeuL3NfzE0ZEYF/B0eh3ideiMCybUL8dZ59b0gKSOBao7/3AD5oaWXpHeIPP7L0gko2+eunP/isrK59QkjcVY3e18QCLnfQyGPvnbdbmLUdT92HaTGIOe9Glim7uD10kipcbiTflg+eu+uwarVMC9P3OLTfy/W8NrWF7Sot4fcQS5h7E8IDhnd74nS0eifdQYQ8plwvFM4cO/dL7r+g2+l6+e/E5+tsMKijs0n2nbzVBBUhQ36r4c+14cPHAhoEYeR2zyZNktbdUQMSiSc82poh5umdaHk2w3hZxYNw5/8OoCtF/nuSJ6rPK3TknYSgpNmGS1gkJ5Y8ePjJ4FIYrsOY/Uy5v2386o3L70jEpWRUFEEQR3pB2nDLnEbYm9Lrdka4tIPEiMylSoK3a1nTLtASTXGZQynRaMT845atYUqoBUyZkmcmQTpUmvQei2EuG9kj2Vr+CMEi/KD/O85iitZrjZx37wLwvEj/zjZTJgrRLOkx/4GJbKxNz8Ep4zkiTPEOUFT0cUeshys94/33SsL4LSjvyFKOsdy8aTfvb39nBZRuTE=
    # SAUCE_TOKENS
    # - secure: m9BMEAR49UjfnSITCWkW0b6RsJ6TwP+EexDNJaEeSZsODOzYK6zR1JKQBVgF5JhSnuZjkXBmncdax1LirADhEw504Bl3a/zMlxQm+GpwTcMHikZQCXTRUtZOKCq31AM8pufAK/9fGFPAdUtgt4takc0RaBrS/tFbDKGOsUy+3H/ymZSI2BGBlrKZD+gaZzlX9dnEY2EwwJKHdFvnjf14eVab1DUXav0I9+C3873YgCfLtTf+/Rzb9SeSuCK6jZq3sHffDIfYWtYo5cgNcNBiEmDGGeLDZ/nHDDj2gmcOsO4yjhEvluFg8cOzQMb+5jhxBYL11nBiEU+zvfaVHssZrDIlPYearhE87w3lN3oXoSqpHqzsFu3WssRsl/j0OvDVmF8eHKSOdPz2ZOhlmiV2ZUrszP17+ocS5c22gTAP/mHUNlCsSOFaZNioV2EQ2ljJkM2q+aoEIbTN1Y/99StsJ1gcVpVReZl5PGCsq+R8J6eXrbTwvC86hAM4/uEStIlKJzIYpvQasgNDa4VLEw9DXECWFRZ1xZfaKf4dnGlLrxh1EcWmBPOmVEsWWaFRhCC6THTB6Rpchekcmh/L8WH9Rxw52ctsiliDG84KS/PjMlPCqc5mPhtreghvJatBPT+rKwyU54k83oouqWkfMVtJewVmT4jtw89a7sVwgTH6dfk=
    # - secure: T1JCtjz7KiSVjL/HJ6t1MShL7J43E2bEp6Mq9ki/0K9ZUUBVfSwyPdDu5sxl0oaW27UmYajq/bp3v+C3gdjkFkO35Te4iKyyC8lVL86IvXvIzDlAMP3ILY6VaaaBKVyGx8iWSTWE+oL3wx2Z7Jed1kw96HeJUrWQhC5KWiV1Ar0imq0jreoBd7+3SgIcKCq/UJmSEHea2HP2DTlPexr/CE1Dp9nYzgJa2goHLidlUCgo6WE9b72EbjqW77ww0RNUAbcdS4+DuCEoSo/6kTO5akQD5pJGNFjtQUfNzrM9ZaJLJzPmP6sr9pbL4FOeIpreVvAON4mfuExlYfVj78vssO8TfXAYXvBwKXRz9h0epjnTTup+39g5dig+3Spwvnvy9XHoQ1ySucEBHLLp/64vlf9itXEqiPcNRPqXysLRbZh1E3g3aXOgXOrU437kF/92LuT4pSfWJa6z+j+HsjHQhlS7pFM3l8xYOwl5v/Dc72GowZLO8bLbIvkg7UooZm8TOCpbZlFTMJWgMKkOae+19E6sKsqbe2SBVx/09raKa2DYhVNct12BfrNG6Nal10He4U2pvvmlNykWdV4P0kgVe7WUNNtNV1hyrDTsdQPxPBzw5kWMR4S0PJ+73IwzCry8w7iQ9yUh1wyeflFTwjUwlRt1AjOYu1f7b3Q62bzYEb4=

# Npm publish options
before_deploy:
  - npm install babel --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: No1/XCRKCV99MUMZlWwbzJN4ho7FVZ6GuduwjbvIH7DHSY9bjua6LUrJLF2+N9snrIDaIPwmWBZj/ew4PdHEzbUNtZ3RsfjRYysAuYUHqgdlFYIhFc74sSpkJ2I6P1n0yR9kmfupXJnQQwnyyo85lmkvBL+CNLr2B3fkoyJwKyLiB8Qq4RlzDbblSDn8d5H6yBcCUW4YSnO2BxMcTe6nV7v0HTcIP98a6TrRU9r6uz82vyd3wQesaiT349uQOkbYaqbiByP7Z7DJmiiU+4Nvoa8Jw7VwbN3WaLUzRkX3hzQROitSMKDB5OHwt6+AIzTKY3joxtlTF5CNBVxNluIROVEkZoxtTQi8tD0ZbE6ctCKueT/Y+w687hsx2+l2LcgvhvBk6NsOHhRbXfYjDpfoZM4nNcOQNx3px9or9jmrQGz4AgcfAmT+tcM7Ttq42LlQ4JkXMWIwCGUrp29It49/DIIXYeZ6wvrC0WtFYi1GLmET8tpWcOLSO5uzZeXyHJ3M4pn5c9R6R8tUYJc56wlptzrNVO9Jolw23o448RY1TiRegtwQzM5A2WeC/lePXpYps+GLLRuBpv/gFphoel7Z1zEEn/2Ot7uOdh473YjfonnA1Deqh3r+4MexKuOvHjFinmm32nO5KMVMio2ZmN2hn1MTjz5vm/vjM54n+3u2ErQ=
