# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

# Coverage report
after_success:
  - npm run report
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: 4ydD2JBKNT9WfAwn4kZ4j/QpSfbJs8Bbb87byHWUOj6klrSMdLtlykzuqioSXW6ZNNqNgCh4YwhQjNuemUKd4RiyyJdxOWuaxpQxQU1KSyZrLbY+Zad++vFlr7PeuL3NfzE0ZEYF/B0eh3ideiMCybUL8dZ59b0gKSOBao7/3AD5oaWXpHeIPP7L0gko2+eunP/isrK59QkjcVY3e18QCLnfQyGPvnbdbmLUdT92HaTGIOe9Glim7uD10kipcbiTflg+eu+uwarVMC9P3OLTfy/W8NrWF7Sot4fcQS5h7E8IDhnd74nS0eifdQYQ8plwvFM4cO/dL7r+g2+l6+e/E5+tsMKijs0n2nbzVBBUhQ36r4c+14cPHAhoEYeR2zyZNktbdUQMSiSc82poh5umdaHk2w3hZxYNw5/8OoCtF/nuSJ6rPK3TknYSgpNmGS1gkJ5Y8ePjJ4FIYrsOY/Uy5v2386o3L70jEpWRUFEEQR3pB2nDLnEbYm9Lrdka4tIPEiMylSoK3a1nTLtASTXGZQynRaMT845atYUqoBUyZkmcmQTpUmvQei2EuG9kj2Vr+CMEi/KD/O85iitZrjZx37wLwvEj/zjZTJgrRLOkx/4GJbKxNz8Ep4zkiTPEOUFT0cUeshys94/33SsL4LSjvyFKOsdy8aTfvb39nBZRuTE=
    # SAUCE_TOKENS
    - secure: cb6srdDmpRD5TE7KnquFAIPQlh6NyH+fP4jIyRGDEtKLzcoB3DyDWBJbSiEFmY0nuheV6RpB7/d3Hcdmmhr92yj/Ha8s8uRWGSRkWeFOrNOXj3S166gfRwYkGVLGqDciVsTqIxL2kZvgNM/d48a5B5Lws3ptWJRfaUcktDFlQX5arGCXgUjVxxK2XBQiM/WV4aWOPYtaxFRc005X+flZAFs2T8bX8meNwNoxRiz476tuy0Y0rYPGEZkeeUFdR8YAfUEq34NhCgEuAbL9L3bu08V+on5ARy+XaxaxVc0G0JlIsrFdHf2YU6VjzEIouryo6EHxOoo/BJPpatFQWG7zcPh097iS37Exz7FZ0J6lOgJxF8Yc9UXTgE0dtwLeK6JPo89Mu5ucWYzfYT3SyU2T05zPdcp6YqmoN5wMtw1t3K3jCjJWvN1tFby1D1jcLMOGk0nhLTHpt2VS2iCVqv2y7OeT19zMNBpQc2JQ5Rce70dd6obGbT+gzxg6Yb/tMlFSrg1DVK697CYvjvXvGIwH+qgN/el8PJhwq69vAnhjqnZNv/POtcv90IaCof/gt5Qg2eVl+oEb6CN2FAH0lY1wvaZtdz58X8+WZ/YXNDZWR29ogXMZ6DZvXykCSxdWS08GQtFtQahMC70bSFa9jsG/RdpYnKUX4JiXhzzzCHj2zd4=
    - secure: rZ25QLIu1Ga+CT8SgZaPuUsPJi+AWF7rkgO0sCBiYl/ETfdMIa51b4tMhEhQnyp2DiIsss/9dh3ts2wWD0h3Q3qI8NwPyd76K1YvxOGb2tUo0Q+ULS4SPWU75CuWAPR6G68U1/HBJJNLeE/dg/yV4UfU5dbATzSnYVwZpzCP1wHxF/a2y9kax2nmEgZnFkFa7YYoWHQgk3hr5H+YRti7N6vxkHxrE7qLKDslBa5Ta1A2sFU+ix7L+X5eTPj/53REBwFvFNJJqyMEwrjWGe0b+P0J89MUBGWPyrbSrfEHROADhDwxO5jrrorbet30ecMKEaa4bxcOBMVR8yEuARfZjRQiGZ4RDxEF0g6Fn+0NQ9EwLrk0cRQMTpiD4TznYe8+zFzhPHrhgZBV4U8ceSQgNHmZEQkXF14E6i/S4C0m7L6gkbLFl7gDDpX7vTWJcpIRypxxcd89cqIjcYfl81RwVIIPkC6Xq/LW1hMTPcVkO+8Jrg3lta6PkOtnf/pgKzMbm9zDfXqyPdIl2by9TeIQx3zBGX6fv/g9gdyFQuAP1aFWHQ8lYyw92NYjyG90fDKKDYn1efkCqvE7tjPTTFuicx/qt/etHnnbKtoc+E49j3rAOkeSA8TaxdOVZ0rMLnOU/KreHD5ye9PGpVHM04qCprSzOlIhS48NmKhob3dw7R0=

# Cloud test(optional)
after_deploy:
  - 'npm install'
  - 'npm run karma && echo perfect || echo good luck'

# Npm publish options
before_deploy:
  - npm install babel --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: No1/XCRKCV99MUMZlWwbzJN4ho7FVZ6GuduwjbvIH7DHSY9bjua6LUrJLF2+N9snrIDaIPwmWBZj/ew4PdHEzbUNtZ3RsfjRYysAuYUHqgdlFYIhFc74sSpkJ2I6P1n0yR9kmfupXJnQQwnyyo85lmkvBL+CNLr2B3fkoyJwKyLiB8Qq4RlzDbblSDn8d5H6yBcCUW4YSnO2BxMcTe6nV7v0HTcIP98a6TrRU9r6uz82vyd3wQesaiT349uQOkbYaqbiByP7Z7DJmiiU+4Nvoa8Jw7VwbN3WaLUzRkX3hzQROitSMKDB5OHwt6+AIzTKY3joxtlTF5CNBVxNluIROVEkZoxtTQi8tD0ZbE6ctCKueT/Y+w687hsx2+l2LcgvhvBk6NsOHhRbXfYjDpfoZM4nNcOQNx3px9or9jmrQGz4AgcfAmT+tcM7Ttq42LlQ4JkXMWIwCGUrp29It49/DIIXYeZ6wvrC0WtFYi1GLmET8tpWcOLSO5uzZeXyHJ3M4pn5c9R6R8tUYJc56wlptzrNVO9Jolw23o448RY1TiRegtwQzM5A2WeC/lePXpYps+GLLRuBpv/gFphoel7Z1zEEn/2Ot7uOdh473YjfonnA1Deqh3r+4MexKuOvHjFinmm32nO5KMVMio2ZmN2hn1MTjz5vm/vjM54n+3u2ErQ=
